<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderOrange.ClientCore\OrderOrange.ClientCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
  </ItemGroup>

  <Target Name="CopyI18n" BeforeTargets="ResolveProjectStaticWebAssets;BeforeBuild">
    <ItemGroup>
      <I18nFile Include="..\OrderOrange.ClientCore\Localization\*.json" />
    </ItemGroup>
    <Copy SourceFiles="@(I18nFile)" DestinationFolder="wwwroot\i18n" SkipUnchangedFiles="true" />
  </Target>

</Project>
