// <auto-generated> Native-speaker list-connectors, one line per language.
// Regenerate with scratchpad/gen-connectors.cs from Tests/bot-multiitem-corpus.json.
// "with"-type particles and the words for punctuation marks are filtered out —
// see BotLexicon.ModifierParticles for why.
namespace OrderOrange.ClientWeb.Services;

public static partial class BotLexicon
{
    public static readonly string[] GeneratedConnectors =
    [
        // ar
        "و", "وبعد", "بعد", "وكمان", "كمان", "ومعاه", "ومعاها", "ويا", "وايضا", "ثم", "بلس", "زياده", "واضف",
        // de
        "und", "plus", "dazu", "und dazu", "noch", "und noch", "dann noch", "außerdem", "ausserdem", "auch", "und auch", "bitte auch", "sowie", "zusätzlich",
        // en
        "and", "plus", "also", "and also", "then", "as well as", "n", "aswell as", "and then", "plus also", "add",
        // es
        "y", "más", "mas", "también", "tambien", "además", "ademas", "aparte", "y aparte", "y también", "y de paso", "junto con", "tmb",
        // fa
        "و", "بعلاوه", "به علاوه", "پلاس", "همچنین", "ضمنا", "در ضمن", "راستی", "هم", "همینطور", "بعدشم",
        // fr
        "et", "plus", "aussi", "et aussi", "puis", "et puis", "ensuite", "ainsi que", "également", "en plus", "et avec ça", "avec ça", "sinon",
        // hi
        "और", "अउर", "और साथ में", "साथ ही", "प्लस", "भी", "और भी", "तथा", "व", "फिर", "aur", "plus", "bhi",
        // it
        "ed", "più", "e anche", "anche", "e poi", "poi", "in più", "oltre a", "pure", "e pure",
        // ja
        "と", "それと", "あと", "あとは", "それから", "そして", "プラス", "ついでに", "追加で", "も", "で", "や",
        // pt
        "mais", "também", "e também", "e mais", "com mais", "e ainda", "ainda", "além de", "e por último", "tambem", "tb",
        // ru
        "плюс", "ещё", "еще", "а ещё", "и ещё", "а также", "также", "потом", "и потом", "вдобавок", "в придачу", "да",
        // tr
        "ve", "bir de", "birde", "bide", "bi de", "ayrıca", "ayrica", "artı", "arti", "ek olarak", "sonra", "bir tane de", "hem de", "ilaveten",
        // ur
        "اور", "اور ساتھ", "ساتھ ہی", "پلس", "بھی", "اور بھی", "اسکے علاوہ", "مزید", "پھر", "ایک اور", "او", "نیز",
        // zh
        "和", "还有", "再来", "再要", "再", "加", "加上", "另外", "还要", "然后", "以及", "外加", "顺便",
    ];
}
